version: "3"
services:
  frontend:
    build: ../frontend
    ports:
      - "8080:8080"
    volumes:
      - ../frontend:/usr/src/app
      - /usr/src/app/node_modules
  broker:
    build: ../broker
    ports:
      - "3030:3030"
    volumes:
      - ../broker:/usr/src/app
      - /usr/src/app/node_modules
  pythontest:
    build: ../pythontest
    volumes:
      - ../pythontest:/app
